main: sus.keiger.mlgpvp.MLGPvPPlugin
name: MLGPvP
api-version: 1.21
version: 1.0.0

commands:
  mlgpvp:
    description: Command to manage the MLGPvP plugin
    permission: isOP

permissions:
  isOP:
    description: Is admin
    default: op